In [1]:
import cv2
import os
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import sys
from PyQt5.QtWidgets import QDialog, QApplication, QWidget
from Hw2_1ui import Ui_Dialog

app = QApplication(sys.argv)
form = QWidget()
window = Ui_Dialog()
window.setupUi(form)
form.show
sys.exit(app.exec_())

Extrinsic:
[[-0.10136279 -0.98938015 -0.10417537  4.14227859]
 [ 0.96716542 -0.07346929 -0.24329676 -1.95505232]
 [ 0.23305929 -0.12541606  0.96434132 16.60072064]]


KeyboardInterrupt: 